databases:
  - name: pruebaAIdb
    plan: free
    databaseName: pruebaAI
    user: pruebaAI

services:
  - type: web
    plan: free
    name: pruebaAI
    runtime: python
    buildCommand: "./build.sh"
    startCommand: "python -m gunicorn pruebaAI.asgi:application -k uvicorn.workers.UvicornWorker"    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: pruebaAIdb
          property: connectionString
      - key: SECRET_KEY
        generateValue: true
      - key: WEB_CONCURRENCY
        value: 4